// Hindi strings, keyed by the English text. Covers all of Senior mode, sign-in, navigation,
// statuses and the most-used family, booking and settings labels. Anything missing shows in English.
export const HI = {
  // greetings and senior home
  'Good morning': 'सुप्रभात', 'Good afternoon': 'नमस्ते', 'Good evening': 'शुभ संध्या', 'Hello': 'नमस्ते',
  'Read aloud': 'सुनें', 'Are you OK today?': 'क्या आप आज ठीक हैं?', 'I am OK': 'मैं ठीक हूँ', 'I need help': 'मुझे मदद चाहिए',
  "Today's medicines": 'आज की दवाइयाँ', 'Next visit': 'अगली विज़िट', 'Call family': 'परिवार को कॉल करें', 'More help': 'और मदद',
  'Book help, scam check, nurse': 'मदद बुक करें, ठगी जाँच, नर्स', 'SOS emergency. Press and hold for 3 seconds': 'SOS आपातकाल। 3 सेकंड दबाकर रखें',
  'Press and hold 3 seconds': '3 सेकंड दबाकर रखें', 'Keep holding the SOS button for 3 seconds': 'SOS बटन को 3 सेकंड तक दबाए रखें',
  'Send SOS now?': 'अभी SOS भेजें?', 'Yes, send SOS': 'हाँ, SOS भेजें', 'If you need help, press and hold SOS.': 'मदद चाहिए तो SOS दबाकर रखें।',
  'medicines to take now': 'दवाइयाँ अभी लेनी हैं', 'You have': 'आपको', 'now': 'अभी', 'taken': 'ली गईं', 'None booked': 'कोई बुकिंग नहीं',
  'Caregiver to be assigned': 'देखभालकर्ता तय होना बाकी', 'How was the visit?': 'विज़िट कैसी रही?', 'tap to give stars': 'सितारे देने के लिए छुएँ',
  'Tap to see what is happening': 'क्या हो रहा है, देखने के लिए छुएँ', 'Help is on the way': 'मदद आ रही है', 'Waiting for your family': 'परिवार की मंज़ूरी का इंतज़ार',
  'they have been asked to approve': 'उनसे मंज़ूरी माँगी गई है', 'Important': 'ज़रूरी', 'This week': 'इस हफ़्ते',
  // medicines
  'Taken': 'ले ली', 'Later': 'बाद में', 'Skip': 'छोड़ें', 'Skipped': 'छोड़ी', 'Missed': 'छूट गई', 'Well done!': 'बहुत अच्छे!',
  'All medicines for now are taken.': 'अभी की सारी दवाइयाँ ले ली गई हैं।', 'No medicines due right now.': 'अभी कोई दवा लेनी नहीं है।', 'No medicines today.': 'आज कोई दवा नहीं।',
  'We will remind you again in 15 minutes': 'हम 15 मिनट में फिर याद दिलाएँगे', 'Your family will be told that you skipped this dose': 'परिवार को बताया जाएगा कि आपने यह खुराक छोड़ी',
  'ElderLink only reminds you of what your doctor prescribed. Ask your doctor before changing any medicine.': 'ElderLink केवल डॉक्टर की लिखी दवा याद दिलाता है। कोई भी दवा बदलने से पहले डॉक्टर से पूछें।',
  'after food': 'खाने के बाद', 'before food': 'खाने से पहले', 'with food': 'खाने के साथ', 'critical': 'बहुत ज़रूरी', 'Medicines': 'दवाइयाँ',
  // visit
  'Your visit code': 'आपका विज़िट कोड', 'Your visit code is': 'आपका विज़िट कोड है', 'Read the code aloud': 'कोड सुनें',
  'Tell this code to the nurse only when they are at your door. It proves the visit happened.': 'यह कोड नर्स को तभी बताएँ जब वह आपके दरवाज़े पर हो। इससे विज़िट पक्की होती है।',
  'Call the caregiver': 'देखभालकर्ता को कॉल करें', 'The caregiver has checked in.': 'देखभालकर्ता पहुँच गए हैं।', 'No visit is booked.': 'कोई विज़िट बुक नहीं है।',
  'Visit code': 'विज़िट कोड', 'share only when the caregiver is at the door': 'देखभालकर्ता दरवाज़े पर हो तभी बताएँ',
  // family call
  'Calling': 'कॉल हो रही है', 'Talking to you': 'आपसे बात', 'End call': 'कॉल खत्म करें', 'Video call (simulated in this demo)': 'वीडियो कॉल (डेमो में नकली)',
  'son': 'बेटा', 'daughter': 'बेटी', 'grandson': 'पोता', 'granddaughter': 'पोती', 'daughter-in-law': 'बहू', 'son-in-law': 'दामाद', 'neighbour': 'पड़ोसी',
  // more / help
  'Ask for help at home': 'घर पर मदद माँगें', 'Ask for help': 'मदद माँगें', 'Is this call a scam?': 'क्या यह कॉल ठगी है?', 'Talk to a nurse (24x7)': 'नर्स से बात करें (24x7)',
  'Classes and events': 'कक्षाएँ और कार्यक्रम', 'Make the screen easier': 'स्क्रीन आसान बनाएँ', 'Text size': 'अक्षर का आकार', 'High contrast': 'गहरे रंग',
  'Normal colours': 'सामान्य रंग', 'Language': 'भाषा', 'Settings': 'सेटिंग्स',
  'Choose one. We find a trusted, verified person nearby and ask your family to approve.': 'एक चुनें। हम पास का भरोसेमंद, जाँचा हुआ व्यक्ति ढूँढेंगे और परिवार से मंज़ूरी लेंगे।',
  'Nurse at home': 'घर पर नर्स', 'Attendant for the day': 'दिन भर के लिए सहायक', 'Someone to take me to hospital': 'अस्पताल ले जाने के लिए कोई', 'Groceries, bank or bills': 'राशन, बैंक या बिल',
  'Your family has been asked to approve.': 'परिवार से मंज़ूरी माँगी गई है।', 'A coordinator will call you shortly.': 'कोऑर्डिनेटर जल्द आपको कॉल करेंगे।',
  'What is the problem? (you can leave this empty)': 'क्या परेशानी है? (खाली छोड़ सकते हैं)', 'Call me now': 'मुझे अभी कॉल करें', 'Send': 'भेजें',
  'Thank you for telling us': 'बताने के लिए धन्यवाद', 'Thank you!': 'धन्यवाद!', 'Thank you! Have a good day.': 'धन्यवाद! आपका दिन शुभ हो।', 'Done.': 'हो गया।',
  // scam
  'Never share your OTP, PIN or password with anyone.': 'अपना OTP, PIN या पासवर्ड किसी को न बताएँ।', 'ElderLink, banks and police never ask for them.': 'ElderLink, बैंक और पुलिस कभी नहीं माँगते।',
  'Verify before you pay': 'पैसे देने से पहले जाँचें', 'Report a strange call or message': 'अजीब कॉल या मैसेज की शिकायत करें', 'I think I lost money': 'मुझे लगता है पैसे चले गए',
  'Act fast': 'तुरंत कदम उठाएँ', 'Call 1930 now': 'अभी 1930 पर कॉल करें', 'Call 1930 now.': 'अभी 1930 पर कॉल करें।', 'Your family has been alerted.': 'परिवार को सूचना दे दी गई है।',
  'Call 1930 (National Cyber Crime Helpline) right now. Speed matters to freeze the money.': 'अभी 1930 (राष्ट्रीय साइबर अपराध हेल्पलाइन) पर कॉल करें। जल्दी करने से पैसा रुक सकता है।',
  'File a complaint at cybercrime.gov.in and note the reference number.': 'cybercrime.gov.in पर शिकायत दर्ज करें और नंबर लिख लें।',
  'Call your bank to block the card / UPI and dispute the payment.': 'बैंक को कॉल करके कार्ड / UPI बंद करवाएँ और भुगतान पर आपत्ति दर्ज करें।',
  'Do not call back the scammer or share any more details.': 'ठग को वापस कॉल न करें, कोई और जानकारी न दें।',
  'Do not answer or call back the number.': 'उस नंबर को न उठाएँ, न वापस कॉल करें।', 'Never share OTP, PIN or passwords. ElderLink and banks never ask for them.': 'OTP, PIN या पासवर्ड कभी न बताएँ। ElderLink और बैंक कभी नहीं माँगते।',
  'A coordinator will call you with advice.': 'कोऑर्डिनेटर आपको सलाह के लिए कॉल करेंगे।',
  // rating
  'Stars': 'सितारे', 'stars': 'सितारे', 'Kind': 'दयालु', 'On time': 'समय पर', 'Skilled': 'कुशल', 'Clean': 'साफ़-सुथरे', 'Late': 'देर से', 'rude': 'रूखा व्यवहार', 'did not come': 'नहीं आए', 'unsafe': 'असुरक्षित',
  // SOS live
  'Help is coming': 'मदद आ रही है', 'Help is coming. Stay calm.': 'मदद आ रही है। शांत रहें।', 'Stay calm. Keep your phone near you. Your family has been told.': 'शांत रहें। फ़ोन पास रखें। परिवार को बता दिया गया है।',
  'Help is coming. Our emergency team will call you now. Your family has been told.': 'मदद आ रही है। हमारी आपात टीम अभी आपको कॉल करेगी। परिवार को बता दिया गया है।',
  'We are calling you now. Your family has been told.': 'हम अभी आपको कॉल कर रहे हैं। परिवार को बता दिया गया है।',
  'SOS received': 'SOS मिल गया', 'Emergency desk is calling you': 'आपात डेस्क आपको कॉल कर रहा है', 'Help is being arranged': 'मदद की व्यवस्था हो रही है',
  'Ambulance on the way': 'एम्बुलेंस रास्ते में है', 'No emergency is open.': 'कोई आपात स्थिति खुली नहीं है।', 'Call 112': '112 पर कॉल करें', 'Call 108 ambulance': '108 एम्बुलेंस को कॉल करें',
  'No data connection: sending SMS with your location and calling the SOS number': 'इंटरनेट नहीं है: आपकी लोकेशन SMS से भेजी जा रही है और SOS नंबर पर कॉल हो रही है',
  // events
  'Join': 'जुड़ें', 'You are going': 'आप जा रहे हैं', 'going': 'जा रहे हैं', 'Online': 'ऑनलाइन', 'You are registered. We will remind you.': 'आपका नाम लिख लिया है। हम याद दिलाएँगे।',
  'You will get a reminder on the day.': 'उस दिन आपको याद दिलाया जाएगा।',
  // common words
  'Back': 'वापस', 'Close': 'बंद करें', 'Yes': 'हाँ', 'No': 'नहीं', 'OK': 'ठीक है', 'Continue': 'आगे बढ़ें', 'Save': 'सेव करें', 'Cancel': 'रद्द करें', 'Open': 'खोलें',
  'Today': 'आज', 'Tomorrow': 'कल', 'Yesterday': 'बीता कल', 'just now': 'अभी-अभी', 'min ago': 'मिनट पहले', 'h ago': 'घंटे पहले', 'min': 'मिनट', 'about': 'लगभग',
  'Loading...': 'लोड हो रहा है...', 'Sorry, something went wrong': 'माफ़ कीजिए, कुछ गड़बड़ हुई', 'Go home': 'होम पर जाएँ', 'Skip to content': 'मुख्य भाग पर जाएँ',
  'Main menu': 'मुख्य मेनू', 'Change language': 'भाषा बदलें', 'Notifications': 'सूचनाएँ', 'More': 'और', 'Removed': 'हटाया गया', 'optional': 'वैकल्पिक',
  'No readings yet': 'अभी कोई रीडिंग नहीं', 'Voice is not available on this device': 'इस फ़ोन पर आवाज़ उपलब्ध नहीं है', 'Voice call': 'वॉइस कॉल', 'To': 'को',
  'No senior profile yet.': 'अभी कोई वरिष्ठ प्रोफ़ाइल नहीं।', 'held: quiet hours': 'रोका गया: शांत समय',
  // sign in
  'Trusted care for your parents, near their home': 'आपके माता-पिता के लिए भरोसेमंद देखभाल, उनके घर के पास',
  'Verified nurses, hospitals and helpers with clear minimum prices and real reviews. Plus medicine reminders, monthly check visits and 24x7 SOS.': 'जाँची हुई नर्सें, अस्पताल और सहायक, साफ़ न्यूनतम दाम और असली समीक्षाओं के साथ। साथ में दवा रिमाइंडर, मासिक जाँच विज़िट और 24x7 SOS।',
  'Try the demo as': 'डेमो इस रूप में देखें', 'Pick a person to see the app from their side. Everything is sample data; no real payments, SMS or calls.': 'किसी व्यक्ति को चुनें और उसकी नज़र से ऐप देखें। सब नमूना डेटा है; कोई असली भुगतान, SMS या कॉल नहीं।',
  'Sign in or create an account': 'साइन इन करें या खाता बनाएँ', 'Mobile number': 'मोबाइल नंबर', 'Indian or international': 'भारतीय या विदेशी', 'Send OTP': 'OTP भेजें',
  'Enter the 6-digit code': '6 अंकों का कोड डालें', 'Code sent by SMS.': 'कोड SMS से भेजा गया।', 'Demo code': 'डेमो कोड', 'Your name': 'आपका नाम', 'I am': 'मैं हूँ',
  'A family member arranging care for a parent': 'माता-पिता की देखभाल करने वाला परिवार का सदस्य', 'A senior citizen (60+)': 'वरिष्ठ नागरिक (60+)',
  'A nurse, attendant, physio or helper': 'नर्स, सहायक, फ़िज़ियो या मददगार', 'A hospital, nursing home or agency': 'अस्पताल, नर्सिंग होम या एजेंसी',
  'Your consent': 'आपकी सहमति', 'We ask separately for each use of your data. You can withdraw any time from Settings.': 'हम आपके डेटा के हर उपयोग के लिए अलग से पूछते हैं। आप कभी भी सेटिंग्स से वापस ले सकते हैं।',
  'needed to use ElderLink': 'ElderLink इस्तेमाल के लिए ज़रूरी', 'I agree to the required uses above': 'मैं ऊपर के ज़रूरी उपयोगों से सहमत हूँ',
  'ElderLink coordinates care and emergencies; it does not provide ambulance or medical treatment itself.': 'ElderLink देखभाल और आपात स्थिति का तालमेल करता है; यह खुद एम्बुलेंस या इलाज नहीं देता।',
  'Care delivery (booking and visits)': 'देखभाल सेवा (बुकिंग और विज़िट)', 'Sharing with my care circle (family members I invite)': 'मेरे केयर सर्कल (मेरे बुलाए परिवार) के साथ साझा करना',
  'Processing health details (conditions, medicines, vitals)': 'स्वास्थ्य जानकारी (बीमारी, दवाइयाँ, जाँच) का उपयोग', 'Offers and news from ElderLink': 'ElderLink से ऑफ़र और खबरें',
  'Care coordinator': 'केयर कोऑर्डिनेटर', 'Emergency desk (24x7)': 'आपात डेस्क (24x7)', 'Admin': 'एडमिन', 'Family: son in Dubai': 'परिवार: दुबई में बेटा', 'Senior: Kamala, 78': 'वरिष्ठ: कमला, 78',
  'Caregiver: nurse Priya': 'देखभालकर्ता: नर्स प्रिया', 'Hospital: Lakeside admin': 'अस्पताल: लेकसाइड एडमिन',
  "Uses the big-button Senior mode: today's medicines, next visit, call family and SOS.": 'बड़े बटन वाला वरिष्ठ मोड: आज की दवाइयाँ, अगली विज़िट, परिवार को कॉल और SOS।',
  'Pays for care for his parents in Bengaluru. Books, approves, tracks visits, medicines and SOS from afar.': 'बेंगलुरु में माता-पिता की देखभाल का खर्च उठाते हैं। दूर से बुकिंग, मंज़ूरी, विज़िट, दवा और SOS देखते हैं।',
  'Senior citizen': 'वरिष्ठ नागरिक', 'Son in Dubai': 'दुबई में बेटा', 'Independent nurse': 'स्वतंत्र नर्स', 'Hospital admin': 'अस्पताल एडमिन', 'New nurse applying': 'आवेदन करती नई नर्स',
  'Emergency desk': 'आपात डेस्क', 'Platform admin': 'प्लेटफ़ॉर्म एडमिन',
  // demo panel
  'Demo': 'डेमो', 'Demo controls': 'डेमो कंट्रोल', 'Demo time': 'डेमो समय', 'Switch person': 'व्यक्ति बदलें', 'Reset demo data': 'डेमो डेटा रीसेट करें', 'Demo data reset': 'डेमो डेटा रीसेट हो गया',
  'Time moved': 'समय आगे बढ़ा', 'Time moved forward': 'समय आगे बढ़ा', 'Phone messages': 'फ़ोन संदेश', 'Phone messages (SMS, WhatsApp, calls)': 'फ़ोन संदेश (SMS, WhatsApp, कॉल)',
  'Simulate no mobile data (SOS falls back to SMS and call)': 'मोबाइल डेटा बंद मानें (SOS, SMS और कॉल से जाएगा)', 'Mobile data is now off (simulated)': 'मोबाइल डेटा अब बंद है (नकली)', 'Mobile data is back on': 'मोबाइल डेटा फिर चालू',
  'Payments, SMS, WhatsApp and calls are simulated. Use these controls to switch person and move time forward to see reminders, alerts and payouts happen.': 'भुगतान, SMS, WhatsApp और कॉल नकली हैं। व्यक्ति बदलने और समय आगे बढ़ाकर रिमाइंडर, अलर्ट और भुगतान देखने के लिए इन्हें इस्तेमाल करें।',
  'Running fully in this browser; data is saved on this device.': 'पूरा ऐप इसी ब्राउज़र में चल रहा है; डेटा इसी डिवाइस पर सेव है।', 'Connected to the ElderLink server.': 'ElderLink सर्वर से जुड़ा है।',
  'Every SMS, WhatsApp message and automated call the system has sent, newest first. In production these go through DLT-registered SMS, WhatsApp Business and IVR providers.': 'सिस्टम के भेजे सभी SMS, WhatsApp संदेश और ऑटो कॉल, नए पहले। असली ऐप में ये DLT-पंजीकृत SMS, WhatsApp Business और IVR से जाते हैं।',
  'No messages yet.': 'अभी कोई संदेश नहीं।',
  // navigation
  'Home': 'होम', 'Find care': 'देखभाल ढूँढें', 'Bookings': 'बुकिंग', 'My services': 'मेरी सेवाएँ', 'Earnings': 'कमाई', 'Academy': 'अकादमी', 'Profile': 'प्रोफ़ाइल',
  'Dashboard': 'डैशबोर्ड', 'Staff': 'स्टाफ़', 'Services': 'सेवाएँ', 'Payouts': 'भुगतान', 'Overview': 'सारांश', 'SOS desk': 'SOS डेस्क', 'Verification': 'सत्यापन',
  'Check visits': 'जाँच विज़िट', 'Quality': 'गुणवत्ता', 'Complaints': 'शिकायतें', 'Reports': 'रिपोर्ट', 'Rules and prices': 'नियम और दाम', 'Catalogue': 'सूची', 'Operations': 'संचालन', 'Audit log': 'ऑडिट लॉग',
  // booking statuses
  'Needs approval': 'मंज़ूरी चाहिए', 'Waiting for provider': 'प्रदाता का इंतज़ार', 'Accepted': 'स्वीकार', 'Caregiver assigned': 'देखभालकर्ता तय', 'Visit in progress': 'विज़िट चल रही है',
  'Done: please confirm': 'पूरा: कृपया पुष्टि करें', 'Confirmed': 'पुष्टि हो गई', 'Completed': 'पूरा हुआ', 'Declined, refunded': 'मना किया, पैसा वापस', 'Not accepted, refunded': 'स्वीकार नहीं, पैसा वापस',
  'Cancelled': 'रद्द', 'No-show, refunded': 'नहीं आए, पैसा वापस', 'Issue raised': 'शिकायत दर्ज',
  // family home and booking
  'Bengaluru': 'बेंगलुरु', 'All good today': 'आज सब ठीक है', "Today's visits": 'आज की विज़िट', 'Medicines today': 'आज की दवाइयाँ', 'missed': 'छूटी', '7-day adherence': '7 दिन में दवा लेने की दर',
  'Last vitals': 'पिछली जाँच', 'Next check visit': 'अगली जाँच विज़िट', 'Book care': 'देखभाल बुक करें', 'SOS for': 'SOS:', 'Review': 'देखें', 'Confirm': 'पुष्टि करें', 'None': 'कोई नहीं',
  'Spent in the last 30 days': 'पिछले 30 दिनों में खर्च', 'Payments': 'भुगतान', 'Add': 'जोड़ें', 'Add a senior': 'वरिष्ठ जोड़ें', 'plan': 'प्लान', 'No plan': 'कोई प्लान नहीं',
  'Health care': 'स्वास्थ्य देखभाल', 'Packages': 'पैकेज', 'Daily living': 'रोज़मर्रा', 'Company': 'साथ', 'Filters and sort': 'फ़िल्टर और क्रम', 'Sponsored': 'प्रायोजित',
  'per visit': 'प्रति विज़िट', 'visit': 'विज़िट', 'minimum charge': 'न्यूनतम शुल्क', 'Pick a day': 'दिन चुनें', 'Pick a time': 'समय चुनें', 'Repeat': 'दोहराएँ', 'Just once': 'सिर्फ़ एक बार',
  'Weekdays': 'सोम-शुक्र', 'Daily': 'रोज़', 'Weekly': 'हर हफ़्ते', 'Pay': 'भुगतान करें', 'Total': 'कुल', 'Platform fee': 'प्लेटफ़ॉर्म शुल्क', 'Choose a time first': 'पहले समय चुनें',
  'free': 'खाली', 'full': 'भरा', 'Book': 'बुक करें', 'Upcoming': 'आने वाली', 'Past': 'पिछली', 'Who is coming': 'कौन आ रहा है', 'Details': 'विवरण', 'Address': 'पता', 'Price': 'दाम',
  'Timeline': 'समयरेखा', 'Visit report': 'विज़िट रिपोर्ट', 'Confirm visit': 'विज़िट की पुष्टि करें', 'Rate the visit': 'विज़िट को रेट करें', 'Raise an issue': 'शिकायत करें',
  'Cancel booking': 'बुकिंग रद्द करें', 'Keep booking': 'बुकिंग रखें', 'Change time': 'समय बदलें', 'Approve and pay': 'मंज़ूर करें और भुगतान करें', 'Decline': 'मना करें',
  'Vitals': 'जाँच (वाइटल्स)', 'Blood pressure': 'ब्लड प्रेशर', 'Sugar': 'शुगर', 'Pulse': 'नब्ज़', 'Weight': 'वज़न', 'Mood': 'मनोदशा', 'Normal': 'सामान्य', 'Watch': 'ध्यान दें', 'See a doctor': 'डॉक्टर को दिखाएँ',
  'Care circle': 'केयर सर्कल', 'Care plan': 'केयर प्लान', 'Family plan': 'फ़ैमिली प्लान', 'Safety': 'सुरक्षा', 'Document vault': 'दस्तावेज़ तिजोरी', 'Monthly summary': 'मासिक सारांश',
  'Add medicine': 'दवा जोड़ें', 'Scan prescription': 'पर्चा स्कैन करें', 'Print chart': 'चार्ट प्रिंट करें', 'Mark taken': 'ली गई मार्क करें', 'Medicine list': 'दवाओं की सूची',
  'Choose a plan': 'प्लान चुनें', 'Current plan': 'मौजूदा प्लान', 'month': 'महीना', 'year': 'साल', 'Most chosen': 'सबसे ज़्यादा चुना गया',
  // settings and help
  'Easy to read': 'पढ़ने में आसान', 'Senior mode': 'वरिष्ठ मोड', 'Bigger buttons, fewer choices on each screen, voice read-out': 'बड़े बटन, हर स्क्रीन पर कम विकल्प, आवाज़ में पढ़कर सुनाना',
  'Large': 'बड़ा', 'Extra large': 'बहुत बड़ा', 'Theme': 'थीम', 'Same as phone': 'फ़ोन जैसा', 'Light': 'हल्का', 'Dark': 'गहरा', 'Quiet hours': 'शांत समय', 'From': 'से',
  'Your data and consent': 'आपका डेटा और सहमति', 'Withdraw': 'वापस लें', 'Give consent': 'सहमति दें', 'Given': 'दी गई', 'Not given': 'नहीं दी', 'Download my data': 'मेरा डेटा डाउनलोड करें',
  'Delete my account': 'मेरा खाता हटाएँ', 'Help and complaints': 'मदद और शिकायतें', 'Sign out': 'साइन आउट', 'Urgent?': 'जल्दी है?', 'Emergency': 'आपातकाल', 'Ambulance': 'एम्बुलेंस',
  'Cyber fraud': 'साइबर ठगी', 'Make a complaint': 'शिकायत करें', 'About': 'किस बारे में', 'What happened?': 'क्या हुआ?', 'Send complaint': 'शिकायत भेजें', 'My complaints': 'मेरी शिकायतें',
  'No complaints.': 'कोई शिकायत नहीं।', 'Grievance officer': 'शिकायत अधिकारी', 'Received': 'मिली', 'Being looked at': 'जाँच चल रही है', 'Resolved': 'हल हो गई',
  'No-show': 'नहीं आए', 'Quality of care': 'देखभाल की गुणवत्ता', 'Behaviour': 'व्यवहार', 'Safety / abuse': 'सुरक्षा / दुर्व्यवहार', 'Billing': 'बिल', 'Data privacy': 'डेटा गोपनीयता', 'App issue': 'ऐप की समस्या',
  'Mark all read': 'सब पढ़ा हुआ मार्क करें', 'new': 'नया', 'urgent': 'तुरंत',
  'Nothing yet. Updates about visits, medicines and SOS appear here.': 'अभी कुछ नहीं। विज़िट, दवा और SOS की खबरें यहाँ दिखेंगी।',
  'Urgent alerts (SOS, missed critical medicine, abnormal vitals) also come by SMS and a phone call, even during quiet hours.': 'ज़रूरी अलर्ट (SOS, छूटी ज़रूरी दवा, असामान्य जाँच) शांत समय में भी SMS और फ़ोन कॉल से आते हैं।',
  'We reply within 48 hours and resolve within 30 days. Safety concerns get a call within 1 hour.': 'हम 48 घंटे में जवाब देते हैं और 30 दिन में हल करते हैं। सुरक्षा की चिंता पर 1 घंटे में कॉल आती है।',
  'Medicine running low': 'दवा कम बची है', 'Approval needed': 'मंज़ूरी चाहिए', 'Visit report ready': 'विज़िट रिपोर्ट तैयार है', 'Approved': 'मंज़ूर', 'Caregiver arrived': 'देखभालकर्ता पहुँचे',
  'Booking accepted': 'बुकिंग स्वीकार', 'SOS: emergency alert': 'SOS: आपात अलर्ट', 'Emergency desk responding': 'आपात डेस्क जवाब दे रहा है', 'SOS closed': 'SOS बंद',
};
